### ISSUE TITLE
docs[passbolt]: Sobre/Utilização da ferramenta.

### ISSUE THREAD

**Issue by guialvesp1** [basedosdados/iac#60]

**Comment by guialvesp1** [comment]
Realizei um breve documento:

# Passbolt

O nosso gerenciador de senhas é o [Passbolt](https://www.passbolt.com/). Ele é um software de código aberto que permite que você gerencie suas senhas de forma segura e compartilhe-as com seus colegas de trabalho.

O primeiro acesso é realizado através da web [neste link](https://passbolt.basedosdados.org), para tal é necessário que a gerência da equipe tenha realizado previamente o cadastro do seu e-mail. Após o primeiro acesso, você pode baixar o aplicativo para celular e/ou plugin para o navegador.

## Como cadastrar uma nova conta?

Esta responsabilidade é da gerência da equipe. Para cadastrar uma nova conta é necessário que a pessoa tenha um e-mail válido do domínio `basedosdados.org`. Para cadastrar uma nova conta, acesse a lista de usuários no [link](https://passbolt.basedosdados.org/app/users), seleciona a opção de adicionar um novo usuário e preencha os campos com os dados da pessoa.

A pessoa receberá um e-mail com um link para ativação da conta e cadastro de senha. Concluído tal cadastro a gerencia da equipe deve adicionar a pessoa na equipe correspondente.

## Como adicionar uma pessoa na minha equipe?

Note que na plataforma sempre é exibido um menu nomeado `Todos os Grupos` na lateral esquerda, onde é apresentado todos os grupos a qual você tem acesso. Com o mouse sobre o grupo, clique no botão `...` e selecione a opção `Editar Grupo`. No campo de `Adicionar Pessoas` digite o e-mail da pessoa que deseja adicionar e salve as alterações.

## Como adicionar uma nova senha ao cofre?

Para cadastrar uma nova senha, acesse o menu `Senhas` e clique no botão `Adicionar Senha`. Preencha os campos com os dados da senha e clique em `Salvar`.

Em primeiro momento tal credencial estará disponível apenas para você. Para compartilhar com outros usuários, clique no botão `Compartilhar` e selecione os usuários que deseja compartilhar a senha.

Durante o processo de compartilhamento, voce pode definir o nível de acesso que cada usuário terá. O nível de acesso pode ser `Leitura`, `Edição` ou `Dono`. O nível de acesso `Dono` permite que o usuário possa editar e excluir a senha.

@rdahis @lucascr91 coloco tal documentação na wiki do `iac` ou partiremos para a idéia de criar um repo `docs`?

**Comment by rdahis** [comment]
Ótimo valeu @guialvesp1. Por enquanto põe no `iac` mesmo. Abri uma discussão [aqui](https://github.com/basedosdados/.github/discussions/2) sobre a migração pra documentação unificada. Se quiser acrescentar quaisquer ideias põe lá.
